apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: o6zh5snc0-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-8e57310028.guqe.p3.openshiftapps.com/rhtap/rhtap-qe-dotnet-basic:0240f2d9df5fcb8d0c4a950ddb1b3e5cda1151e5@sha256:ad6959d5548fc0a06b4c89879bc9e341534815bf150ae22dbcf1ff66cc213c57
          name: container-image
